[package]
name = "jidousha-render-core"
description = "Renderer front end and backend interface for the Jidousha engine. Backend-agnostic."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
jidousha-core = { path = "../jidousha-core" }
jidousha-assets = { path = "../jidousha-assets" }
ab_glyph = { version = "0.2.32", default-features = false, features = ["std"] }

[lints]
workspace = true
