//! Every `ui-text.json` and `lines.json` string this build shows, resolved by key at load.
//!
//! Each `W` names one key. `read_words` looks every one of them up when the game
//! starts, so a renamed or missing key stops the game with the key's path rather
//! than leaving a blank on a screen nobody happened to open.

use crate::json::{At, SchemaError};

/// Which file a key is in.
#[derive(Clone, Copy)]
enum File {
    Ui,
    Lines,
}

/// Declares `W`, one variant per key, and the table of where each one lives.
macro_rules! words {
    ($($variant:ident = $file:ident $path:literal),+ $(,)?) => {
        /// One string the game shows, by its content key.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum W {
            $(
                #[doc = $path]
                $variant
            ),+
        }

        const KEYS: &[(W, File, &str)] = &[$((W::$variant, File::$file, $path)),+];
    };
}

words! {
    TopYear = Ui "top_bar.year",
    TopLastSummer = Ui "top_bar.last_summer",
    TopRenown = Ui "top_bar.house_renown",
    TopDoorCountdown = Ui "top_bar.door_countdown",
    TopDoorOpen = Ui "top_bar.door_open",
    TopDoorTags = Ui "top_bar.door_tags",
    SummerHousehold = Ui "summer.household",
    SummerYard = Ui "summer.yard",
    SummerNoChildren = Ui "summer.no_children",
    SummerHelp = Ui "summer.help",
    SheetDream = Ui "hero_sheet.dream",
    SheetBurden = Ui "hero_sheet.burden",
    SheetHeirloom = Ui "hero_sheet.heirloom",
    SheetBlessed = Ui "hero_sheet.blessed",
    SheetLeaves = Ui "hero_sheet.leaves",
    SheetScar = Ui "hero_sheet.scar",
    SheetChildStation = Ui "hero_sheet.child_station",
    SheetStation = Ui "hero_sheet.station",
    SheetDied = Ui "hero_sheet.died",
    SheetLeft = Ui "hero_sheet.left",
    SheetRenownWounded = Ui "hero_sheet.renown_wounded",
    SheetRenownSettled = Ui "hero_sheet.renown_settled",
    SheetRenown = Ui "hero_sheet.renown",
    SheetAptitudeNote = Ui "hero_sheet.aptitude_note",
    SheetAptitudeNoteAdjusted = Ui "hero_sheet.aptitude_note_adjusted",
    SheetWoundedWarning = Ui "hero_sheet.wounded_warning",
    SheetTooYoung = Ui "hero_sheet.too_young",
    SheetTakenUp = Ui "hero_sheet.taken_up",
    SheetFulfilled = Ui "hero_sheet.fulfilled",
    SheetSettled = Ui "hero_sheet.settled",
    SheetDread = Ui "hero_sheet.dread",
    SheetCourage = Ui "hero_sheet.courage",
    SheetPenalty = Ui "hero_sheet.penalty",
    SheetDestinyCome = Ui "hero_sheet.destiny_come",
    SheetDestiny = Ui "hero_sheet.destiny",
    SheetBondGone = Ui "hero_sheet.bond_gone",
    SheetBonds = Ui "hero_sheet.bonds",
    SheetNoBonds = Ui "hero_sheet.no_bonds",
    SheetMoreBonds = Ui "hero_sheet.more_bonds",
    FamilyHeading = Ui "family.heading",
    FamilySubline = Ui "family.subline",
    FamilyTallyNone = Ui "family.tally_none",
    FamilyTallyOne = Ui "family.tally_one",
    FamilyTallyMany = Ui "family.tally_many",
    FamilyTally = Ui "family.tally",
    FamilyHelp = Ui "family.remembrance_help",
    FamilyLivingStation = Ui "family.living_station",
    FamilyLivingTooYoung = Ui "family.living_too_young",
    FamilyLivingDone = Ui "family.living_done",
    FamilyLivingWants = Ui "family.living_wants",
    FamilyLivingBurden = Ui "family.living_burden",
    FamilyLivingNoFear = Ui "family.living_no_fear",
    FamilyLivingBroken = Ui "family.living_broken",
    FamilyLivingFears = Ui "family.living_fears",
    FamilyLivingSeer = Ui "family.living_seer",
    FamilyOpen = Ui "family.buttons.open",
    FamilyClose = Ui "family.buttons.close",
    FearStateBornBrave = Lines "fear.state_born_brave",
    FearStateConquered = Lines "fear.state_conquered",
    FearStateBroken = Lines "fear.state_broken",
    FearState = Lines "fear.state",
    FearEffect = Lines "fear.effect",
    FearEffectConquered = Lines "fear.effect_conquered",
    FearEffectBroken = Lines "fear.effect_broken",
    QuestCardYouBring = Ui "quest_card.you_bring",
    QuestCardFear = Ui "quest_card.fear",
    QuestCardFearfulItem = Ui "quest_card.fearful_item",
    QuestCardSteadied = Ui "quest_card.steadied",
    AtPlace = Lines "common.at_place",
    ScarBroken = Lines "scar.broken",
    ScarBrokenByGrief = Lines "scar.broken_by_grief",
    DeedBroken = Lines "deed.broken",
    DeedBrokenByGrief = Lines "deed.broken_by_grief",
    DeedConqueredFear = Lines "deed.conquered_fear",
    FearBroken = Lines "fear.broken",
    FearConquered = Lines "fear.conquered",
    GriefRival = Lines "grief.rival",
    GriefDread = Lines "grief.dread",
    GriefBorneOne = Lines "grief.borne_one",
    GriefBorneSharedKinship = Lines "grief.borne_shared_kinship",
    GriefBorneMany = Lines "grief.borne_many",
    QuestCardDreamers = Ui "quest_card.dreamers",
    QuestCardGhost = Ui "quest_card.ghost",
    QuestSheetDreamCall = Ui "quest_sheet.dream_call",
    DreamCounted = Lines "dream.counted",
    DreamStageDone = Lines "dream.stage_done",
    DreamBearingOwned = Lines "dream.bearing_owned",
    DreamBearingOwn = Lines "dream.bearing_own",
    DreamFulfilledOwned = Lines "dream.fulfilled_owned",
    DreamFulfilled = Lines "dream.fulfilled",
    DeedDreamStep = Lines "deed.dream_step",
    DeedDreamFulfilled = Lines "deed.dream_fulfilled",
    BondDreamRivals = Lines "bond.dream_rivals",
    LegacyHandsFull = Lines "legacy.hands_full",
    LegacyHungOverHearth = Lines "legacy.hung_over_hearth",
    LegacyHeirloom = Lines "legacy.heirloom",
    LegacyTale = Lines "legacy.tale",
    LegacyBlessing = Lines "legacy.blessing",
    DeedLeftLegacy = Lines "deed.left_legacy",
    QuestCardDanger = Ui "quest_card.danger",
    QuestCardNeeds = Ui "quest_card.needs",
    QuestCardSucceed = Ui "quest_card.succeed",
    QuestCardTriumph = Ui "quest_card.triumph",
    QuestCardSetback = Ui "quest_card.setback",
    QuestCardDisaster = Ui "quest_card.disaster",
    QuestCardNoOne = Ui "quest_card.no_one",
    QuestCardRoomFor = Ui "quest_card.room_for",
    QuestCardRenown = Ui "quest_card.renown",
    QuestCardUnanswered = Ui "quest_card.unanswered",
    QuestCardWillNotGo = Ui "quest_card.will_not_go",
    QuestSheetNeeds = Ui "quest_sheet.needs",
    QuestSheetNoOne = Ui "quest_sheet.no_one",
    QuestSheetYouBring = Ui "quest_sheet.you_bring",
    QuestSheetDice = Ui "quest_sheet.dice",
    QuestSheetTriumph = Ui "quest_sheet.triumph",
    QuestSheetSuccess = Ui "quest_sheet.success",
    QuestSheetSetback = Ui "quest_sheet.setback",
    QuestSheetDisaster = Ui "quest_sheet.disaster",
    QuestSheetUnanswered = Ui "quest_sheet.unanswered",
    QuestSheetNotQuested = Ui "quest_sheet.not_quested",
    QuestSheetHistory = Ui "quest_sheet.history",
    QuestSheetFallen = Ui "quest_sheet.fallen",
    QuestSheetFewerSeats = Ui "quest_sheet.fewer_seats",
    QuestSheetTroubleStakes = Ui "quest_sheet.trouble_stakes",
    PowerLineMember = Ui "quest_sheet.power_line_member",
    PowerLineCarries = Ui "quest_sheet.power_line_carries",
    PowerLineFears = Ui "quest_sheet.power_line_fears",
    PowerLineConquered = Ui "quest_sheet.power_line_conquered",
    PowerLineWounded = Ui "quest_sheet.power_line_wounded",
    PowerLineDoor = Ui "quest_sheet.power_line_door",
    PowerLineBlessed = Ui "quest_sheet.power_line_blessed",
    PowerLineFloor = Ui "quest_sheet.power_line_floor",
    PowerLineBond = Ui "quest_sheet.power_line_bond",
    PowerLinePatron = Ui "quest_sheet.power_line_patron",
    YearWord = Lines "turning.year_word",
    YearsWord = Lines "turning.years_word",
    SummerSetOut = Ui "summer.button_set_out",
    SummerStayHome = Ui "summer.button_stay_home",
    SummerUnanswered = Lines "summer.unanswered",
    SummerUnansweredTotal = Lines "summer.unanswered_total",
    SummerMendedAtHome = Lines "summer.mended_at_home",
    QuestDisasterRenown = Lines "quest.disaster_renown",
    QuestReward = Lines "quest.reward",
    QuestRewardEach = Lines "quest.reward_each",
    QuestCarrierBonus = Lines "quest.carrier_bonus",
    QuestLesson = Lines "quest.lesson",
    QuestWoundShielded = Lines "quest.wound_shielded",
    QuestSecondWound = Lines "quest.second_wound",
    FateDiedOfWounds = Lines "fate.died_of_wounds",
    DeedWounded = Lines "deed.wounded",
    QuestBurned = Lines "quest.burned",
    FateBurned = Lines "fate.burned",
    QuestDeath = Lines "quest.death",
    FateFell = Lines "fate.fell",
    DeedSurvivedDisaster = Lines "deed.survived_disaster",
    ScarMended = Lines "scar.mended",
    QuestMended = Lines "quest.mended",
    DeedMended = Lines "deed.mended",
    FateCrowned = Lines "fate.crowned",
    QuestCrowned = Lines "quest.crowned",
    DeedCrowned = Lines "deed.crowned",
    CrownHeirLaysAside = Lines "crown.heir_lays_aside",
    CrownHeirloomLeft = Lines "crown.heirloom_left",
    CrownHeirloomTaken = Lines "crown.heirloom_taken",
    DeathCarrierLoss = Lines "death.carrier_loss",
    DeedFirstQuest = Lines "deed.first_quest",
    DeedTriumph = Lines "deed.triumph",
    FearCourage = Lines "fear.courage",
    FearSteadied = Lines "fear.steadied",
    FearDread = Lines "fear.dread",
    BondRivalsToFriends = Lines "bond.rivals_to_friends",
    DeedBefriended = Lines "deed.befriended",
    BondCompanionsToRivals = Lines "bond.companions_to_rivals",
    BondParentSawChild = Lines "bond.parent_saw_child",
    BondChildSawParent = Lines "bond.child_saw_parent",
    GhostLaid = Lines "ghost.laid",
    DeedLaidGhost = Lines "deed.laid_ghost",
    DestinyShieldedBed = Lines "destiny.shielded_bed",
    DestinyShieldedFire = Lines "destiny.shielded_fire",
    TellingHelp = Ui "telling.help",
    TellingQuietTitle = Ui "telling.quiet_title",
    TellingQuietText = Ui "telling.quiet_text",
    TellingMeanwhile = Ui "telling.meanwhile",
    TellingMeanwhileMore = Ui "telling.meanwhile_more",
    TellingHouseClosed = Ui "telling.house_closed",
    TellingQuestMore = Ui "telling.quest_more",
    TellingRoll = Ui "telling.roll",
    TellingMarginExact = Ui "telling.margin_exact",
    TellingMarginBeat = Ui "telling.margin_beat",
    TellingMarginMissed = Ui "telling.margin_missed",
    TellingNext = Ui "telling.buttons.next",
    TellingToWinter = Ui "telling.buttons.to_winter",
    TellingClosed = Ui "telling.buttons.closed",
    TellingSkip = Ui "telling.buttons.skip",
    EndingClosedWhen = Ui "ending.closed_when",
    EndingAgain = Ui "ending.buttons.again",
    WinterHall = Ui "winter.hall",
    WinterChildren = Ui "winter.children",
    WinterHallHelp = Ui "winter.hall_help",
    WinterFire = Ui "winter.fire",
    WinterFireText = Ui "winter.fire_text",
    WinterTraining = Ui "winter.training",
    WinterTrainingText = Ui "winter.training_text",
    WinterLearner = Ui "winter.learner",
    WinterTeacher = Ui "winter.teacher",
    WinterNoLearner = Ui "winter.no_learner",
    WinterGarden = Ui "winter.garden",
    WinterGardenText = Ui "winter.garden_text",
    WinterTable = Ui "winter.table",
    WinterTableText = Ui "winter.table_text",
    WinterAChild = Ui "winter.a_child",
    WinterHousePlus = Ui "winter.house_plus",
    WinterOwnPlus = Ui "winter.own_plus",
    WinterBenches = Ui "winter.benches",
    WinterBenchesText = Ui "winter.benches_text",
    WinterChild = Ui "winter.child",
    WinterBenchTeacher = Ui "winter.bench_teacher",
    WinterNoChild = Ui "winter.no_child",
    WinterTableHelp = Ui "winter.table_help",
    WinterGardenHelp = Ui "winter.garden_help",
    WinterTrainingHelp = Ui "winter.training_help",
    WinterBenchesHelp = Ui "winter.benches_help",
    WinterFireHelp = Ui "winter.fire_help",
    WinterHelp = Ui "winter.help",
    WinterButton = Ui "winter.button",
    RestHeals = Ui "winter.rest_notes.heals",
    RestCalms = Ui "winter.rest_notes.calms",
    RestRests = Ui "winter.rest_notes.rests",
    CourtNobody = Ui "winter.courtship_notes.NOBODY",
    CourtWaiting = Ui "winter.courtship_notes.WAITING",
    CourtKin = Ui "winter.courtship_notes.KIN",
    CourtRivals = Ui "winter.courtship_notes.RIVALS",
    CourtWedAlready = Ui "winter.courtship_notes.WED_ALREADY",
    CourtTooYoung = Ui "winter.courtship_notes.TOO_YOUNG",
    CourtTooFarApart = Ui "winter.courtship_notes.TOO_FAR_APART",
    CourtWillWed = Ui "winter.courtship_notes.WILL_WED",
    ExcuseChildTeacher = Ui "winter.lesson_excuses.child_teacher",
    ExcuseChildTeacherWasted = Ui "winter.lesson_excuses.child_teacher_wasted",
    ExcuseLearnsNothing = Ui "winter.lesson_excuses.learns_nothing",
    ExcuseLearnsNothingWasted = Ui "winter.lesson_excuses.learns_nothing_wasted",
    ExcuseNeedsTeacher = Ui "winter.lesson_excuses.needs_teacher",
    ExcuseNeedsTeacherWasted = Ui "winter.lesson_excuses.needs_teacher_wasted",
    ExcuseNeedsTeacherNow = Ui "winter.lesson_excuses.needs_teacher_now",
    ExcuseNeedsTeacherNowWasted = Ui "winter.lesson_excuses.needs_teacher_now_wasted",
    ExcuseTeacherKnowsNoMore = Ui "winter.lesson_excuses.teacher_knows_no_more",
    ExcuseTeacherKnowsNoMoreWasted = Ui "winter.lesson_excuses.teacher_knows_no_more_wasted",
    ExcuseTooYoung = Ui "winter.lesson_excuses.too_young",
    ExcuseTooYoungWasted = Ui "winter.lesson_excuses.too_young_wasted",
    ExcuseChildLimit = Ui "winter.lesson_excuses.child_limit",
    ExcuseChildLimitWasted = Ui "winter.lesson_excuses.child_limit_wasted",
    ExcuseBelongsOnBench = Ui "winter.lesson_excuses.belongs_on_bench",
    ExcuseBelongsOnBenchWasted = Ui "winter.lesson_excuses.belongs_on_bench_wasted",
    ExcuseIsNoChild = Ui "winter.lesson_excuses.is_no_child",
    ExcuseIsNoChildWasted = Ui "winter.lesson_excuses.is_no_child_wasted",
    ExcuseBenchNeedsTeacher = Ui "winter.lesson_excuses.bench_needs_teacher",
    ExcuseBenchNeedsTeacherWasted = Ui "winter.lesson_excuses.bench_needs_teacher_wasted",
    WinterWaitsForLearner = Lines "winter.waits_for_learner",
    WinterBenchNoChild = Lines "winter.bench_no_child",
    DeedWed = Lines "deed.wed",
    WinterRivalsMakePeace = Lines "winter.rivals_make_peace",
    WinterCourtingFailed = Lines "winter.courting_failed",
    WinterTaleTold = Lines "winter.tale_told",
    WinterTaleToldAgain = Lines "winter.tale_told_again",
    DeedToldTheTale = Lines "deed.told_the_tale",
    WinterTrainedUnder = Lines "winter.trained_under",
    WinterTrainedAlone = Lines "winter.trained_alone",
    WinterTrained = Lines "winter.trained",
    WinterNewStudent = Lines "winter.new_student",
    DeedTaught = Lines "deed.taught",
    WinterRestBoth = Lines "winter.rest_both",
    WinterRestMended = Lines "winter.rest_mended",
    WinterRestCalmed = Lines "winter.rest_calmed",
    LessonAmount = Lines "lesson.amount",
    TurningWinterTitle = Lines "turning.winter_title",
    TurningQuietWinter = Lines "turning.quiet_winter",
    TurningPageWinter = Ui "turning.page_kinds.WINTER",
    TurningContinued = Ui "turning.continued",
    TurningNext = Ui "turning.buttons.next",
    TurningLast = Ui "turning.buttons.last",
    TurningSkip = Ui "turning.buttons.skip",
    TurningHelp = Ui "turning.help",
    TurningPageDeath = Ui "turning.page_kinds.DEATH",
    TurningPageBirth = Ui "turning.page_kinds.BIRTH",
    TurningPageComingOfAge = Ui "turning.page_kinds.COMING_OF_AGE",
    TurningPageArrival = Ui "turning.page_kinds.ARRIVAL",
    TurningPageYear = Ui "turning.page_kinds.YEAR",
    TurningHeirPrompt = Ui "turning.heir_prompt",
    TurningNoHeir = Ui "turning.buttons.no_heir",
    TurningYearTitle = Lines "turning.year_title",
    TurningDoorCountdown = Lines "turning.door_countdown",
    TurningDoorOpen = Lines "turning.door_open",
    TalesOne = Lines "tales.one",
    TalesMany = Lines "tales.many",
    GhostRaised = Lines "ghost.raised",
    DeathTitle = Lines "death.title",
    DeathLeavesHeirloom = Lines "death.leaves_heirloom",
    DeathLeavesDream = Lines "death.leaves_dream",
    HeirKinshipGrandchildHe = Lines "heir.kinship_grandchild_HE",
    HeirKinshipGrandchildShe = Lines "heir.kinship_grandchild_SHE",
    HeirKinshipSiblingHe = Lines "heir.kinship_sibling_HE",
    HeirKinshipSiblingShe = Lines "heir.kinship_sibling_SHE",
    HeirKinshipHouse = Lines "heir.kinship_house",
    HeirProspect = Lines "heir.prospect",
    HeirNotTheDream = Lines "heir.not_the_dream",
    HeirLaysOneAside = Lines "heir.lays_one_aside",
    HeirLaysAside = Lines "heir.lays_aside",
    DeedInherited = Lines "deed.inherited",
    HeirBuriedWith = Lines "heir.buried_with",
    HeirTakesDream = Lines "heir.takes_dream",
    DeedTookUpDream = Lines "deed.took_up_dream",
    PromiseNoChild = Lines "promise.no_child",
    PromisePasses = Lines "promise.passes",
    BirthTitle = Lines "birth.title",
    BirthNamed = Lines "birth.named",
    BirthBlessingOne = Lines "birth.blessing_one",
    BirthBlessingItem = Lines "birth.blessing_item",
    BirthBlessingMany = Lines "birth.blessing_many",
    BirthBornBrave = Lines "birth.born_brave",
    BirthParentFear = Lines "birth.parent_fear",
    BirthFather = Lines "birth.father",
    BirthMother = Lines "birth.mother",
    BirthOwnFear = Lines "birth.own_fear",
    DeedChildBorn = Lines "deed.child_born",
    AgeTitle = Lines "age.title",
    AgeSeer = Lines "age.seer",
    DeedCameOfAge = Lines "deed.came_of_age",
    ArrivalTitle = Lines "arrival.title",
    ArrivalWho = Lines "arrival.who",
    ArrivalDream = Lines "arrival.dream",
    ArrivalFear = Lines "arrival.fear",
    ArrivalSeer = Lines "arrival.seer",
    DeedArrived = Lines "deed.arrived",
    PhaseChanged = Lines "phase.changed",
    AgeCalling = Lines "age.calling",
    AgeTeachingShows = Lines "age.teaching_shows",
    AgeCarriedDream = Lines "age.carried_dream",
    AgeHasDream = Lines "age.has_dream",
    AgeAvengeDream = Lines "age.avenge_dream",
    AgeGhostDream = Lines "age.ghost_dream",
    AgeRolledDream = Lines "age.rolled_dream",
    TopDoorOutlook = Ui "top_bar.door_outlook",
    TopDoorHelp = Ui "top_bar.door_help",
    SummerTryTheDoor = Ui "summer.button_door",
    DoorSheetEmpty = Ui "door_sheet.empty",
    DoorSheetAllThree = Ui "door_sheet.all_three",
    DoorSheetLock = Ui "door_sheet.lock",
    DoorSheetBonds = Ui "door_sheet.bonds",
    DoorSheetPatron = Ui "door_sheet.patron",
    DoorCardTags = Ui "door_sheet.card_tags",
    DoorCardText = Ui "door_sheet.card_text",
    DoorCardAllThree = Ui "door_sheet.card_all_three",
    DoorCardLock = Ui "door_sheet.card_lock",
    DoorCardOdds = Ui "door_sheet.card_odds",
    DoorCardEmpty = Ui "door_sheet.card_empty",
    DoorPrologue = Lines "door.prologue",
    DoorCompanion = Lines "door.companion",
    DoorWentBeside = Lines "door.went_beside",
    DoorSummary = Lines "door.summary",
    DoorBrought = Lines "door.brought",
    DoorBroughtBlood = Lines "door.brought_blood",
    DoorBroughtPromise = Lines "door.brought_promise",
    DoorBroughtHeirloom = Lines "door.brought_heirloom",
    DoorBroughtBornBrave = Lines "door.brought_born_brave",
    DoorBroughtConqueredYear = Lines "door.brought_conquered_year",
    DoorBroughtConquered = Lines "door.brought_conquered",
    DoorBroughtAfraid = Lines "door.brought_afraid",
    DoorBroughtBlessing = Lines "door.brought_blessing",
    DoorBroughtWounded = Lines "door.brought_wounded",
    DoorDescentArrived = Lines "door.descent_arrived",
    DoorDescentNone = Lines "door.descent_none",
    DoorDescentChildHe = Lines "door.descent_child_HE",
    DoorDescentChildShe = Lines "door.descent_child_SHE",
    DoorDescentParents = Lines "door.descent_parents",
    DoorDescentGrandchildHe = Lines "door.descent_grandchild_HE",
    DoorDescentGrandchildShe = Lines "door.descent_grandchild_SHE",
    DoorDescentGrandparents = Lines "door.descent_grandparents",
    DeedOpenedALock = Lines "deed.opened_a_lock",
    DeedStoodAtTheDoor = Lines "deed.stood_at_the_door",
    DoorVerdictOpened = Lines "door.verdict_opened",
    DoorVerdictFell = Lines "door.verdict_fell",
    DoorVerdictCameHome = Lines "door.verdict_came_home",
    DoorVerdictReturned = Lines "door.verdict_returned",
    DoorVerdictToo = Lines "door.verdict_too",
    TellingDoorHeading = Ui "telling.door_heading",
    TellingDoorIntro = Ui "telling.door_intro",
    TellingDoorIntroMore = Ui "telling.door_intro_more",
    TellingAfterDoor = Ui "telling.buttons.after_door",
    EndingTreeHeadingDoor = Ui "ending.tree_heading_door",
    EndingTreeHeadingClosed = Ui "ending.tree_heading_closed",
    EndingTreeSubline = Ui "ending.tree_subline",
    EndingLivedHere = Ui "ending.lived_here",
    EndingTree = Ui "ending.buttons.tree",
    EndingVerdict = Ui "ending.buttons.verdict",
    FamilyTallyNoneEnding = Ui "family.tally_none_ending",
    // Variant words (DESIGN.md S7).
    QuestOutsidersReward = Lines "quest.outsiders_reward",
    QuestBlackMark = Lines "quest.black_mark",
    DeedBlackMark = Lines "deed.black_mark",
    TurningMarkOne = Lines "turning.mark_one",
    TurningMarksMany = Lines "turning.marks_many",
    DeathLeavesMarks = Lines "death.leaves_marks",
    DeathMarkBuried = Lines "death.mark_buried",
    HeirTakesMark = Lines "heir.takes_mark",
    HeirTakesMarks = Lines "heir.takes_marks",
    HeirMarksBuried = Lines "heir.marks_buried",
    WinterMarriedIn = Lines "winter.married_in",
    WinterUnproven = Lines "winter.unproven",
    ArrivalOutsider = Lines "arrival.outsider",
    BirthLean = Lines "birth.lean",
    CourtshipUnproven = Ui "winter.courtship_notes.UNPROVEN",
    CourtshipMarriesIn = Ui "winter.courtship_notes.MARRIES_IN",
    SheetOutsider = Ui "hero_sheet.outsider",
    SheetOutsiderProven = Ui "hero_sheet.outsider_proven",
    SheetLean = Ui "hero_sheet.lean",
    SheetLeanAfter = Ui "hero_sheet.lean_after",
    SheetMarks = Ui "hero_sheet.marks",
    SheetMarksLine = Ui "hero_sheet.marks_line",
    QuestSheetMarkStake = Ui "quest_sheet.mark_stake",
}

/// The resolved strings, indexable by `W`.
pub struct Words(Vec<String>);

impl std::ops::Index<W> for Words {
    type Output = str;

    fn index(&self, word: W) -> &str {
        &self.0[word as usize]
    }
}

/// Look up every `W` in the two files.
pub fn read_words(ui: At<'_>, lines: At<'_>) -> Result<Words, SchemaError> {
    let lines = lines.key("lines")?;
    let mut out = Vec::with_capacity(KEYS.len());
    for (index, (word, file, path)) in KEYS.iter().enumerate() {
        debug_assert_eq!(
            *word as usize, index,
            "KEYS is in W's order by construction"
        );
        let found = match file {
            // `ui-text.json` nests by dotted path; `lines.json` keys contain the dots.
            File::Ui => path
                .split('.')
                .try_fold(ui.clone(), |at, part| at.key(part))?,
            File::Lines => lines.key(path)?,
        };
        // A leaf is either a plain string or an object carrying `text`.
        out.push(match found.str() {
            Ok(text) => text,
            Err(_) => found.key("text")?.str()?,
        });
    }
    Ok(Words(out))
}
